apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-squad-backend
spec:
  selector:
    matchLabels:
      app: home-squad-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: home-squad-backend
    spec:
      containers:
        - name: home-squad-backend
          image: homesquad:kube-0.1
          ports:
            - containerPort: 4000
              name: "graphql"