apiVersion: v1
kind: Service
metadata:
  name: home-squad-backend-service
spec:
  type: LoadBalancer
  selector:
    app: home-squad-backend
  ports:
    - name: "graphql"
      port: 4000
      targetPort: 4000
      nodePort: 30400