apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-squad-postgres-data-persisent-volume-claim
spec:
  volumeName: home-squad-postgres-data-persisent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi