apiVersion: v1
kind: Service
metadata:
  name: home-squad-frontend-service
spec:
  type: NodePort
  selector:
    app: home-squad-frontend
  ports:
    - name: "react"
      port: 3000
      targetPort: 3000
      nodePort: 30300