apiVersion: v1
kind: Service
metadata:
  name: home-squad-redis-service
spec:
  type: NodePort
  selector:
    app: home-squad-redis
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
      nodePort: 30379